# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    # Runs a set of commands using the runners shell
    - name: Generate static files
      run: |
        yarn install
        yarn docs:build

    - name: Git push
      run:  |
        cd docs/.vuepress/dist
        git init
        git config --global user.name "wquanfeng"
        git config --global user.email "wquanfeng@gmail.com"
        git add -A
        git commit -m 'deploy'
        git push -f https://github.com/if-ls/mooc.git master:gh-pages

